server:
  port: ${PORT:9999}

spring:
  application:
    name: agenda-pro-api-rest
  datasource:
    url: jdbc:mysql://${BD_HOST:localhost}:${BD_PORT:3306}/${BD_NAME:agenda_pro}?createDatabaseIfNotExist=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${BD_USR:root}
    password: ${BD_PWD:root}
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
        use_sql_comments: false
  sql:
    init:
      mode: always
logging:
  level:
    org:
      root: OFF
      springframework: OFF
      hibernate:
        SQL: DEBUG
    org.springframework:
      boot.autoconfigure.jdbc.DataSourceInitializer: DEBUG
      jdbc.datasource.init.ScriptUtils: DEBUG
      security: OFF
      web: OFF